language: go
go:
    - "1.13"

before_install:
    - go get -u golang.org/x/tools/cmd/cover
    - go get -u github.com/mattn/goveralls
    - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sudo sh -s -- -b $(go env GOPATH)/bin v1.18.0

script:
    - go build
    - golangci-lint --version
    - golangci-lint run
    - go test -v ./...
    - go test -v -covermode=count -coverprofile=coverage.out ./diff
    - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci
