language: go
go:
    - "1.13"

before_install:
    - go get -u golang.org/x/tools/cmd/cover
    - go get -u github.com/mattn/goveralls
    - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sudo sh -s -- -b $(go env GOPATH)/bin v1.18.0

script:
    - GOOS=linux CGO_ENABLED=0 go build cmd/prom-liver/main.go
    - go test -v ./...

after_success:
    - golangci-lint --version
    - golangci-lint run
    - curl -XPOST $DOCKER_BUILD_TRIGGER
