{
 "title": "Prom-liver metrics",
 "description": "Golang Application Runtime metrics",
 "tags": [
  "go",
  "golang"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": "label_values(prom_liver_requests_total, job)"
   }
  ]
 },
 "panels": [
  { "title": "Prom-liver", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Reload count [1m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(prom_liver_reload_total[1m])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Remote duration [5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(prom_liver_remote_duration_seconds_bucket[1m]))",
     "legendFormat": "{{function}} percentile 90"
    },
    {
     "expr": "histogram_quantile(0.99, rate(prom_liver_remote_duration_seconds_bucket[1m]))",
     "legendFormat": "{{function}} percentile 99"
    },
    {
     "expr": "rate(prom_liver_remote_duration_seconds_sum[1m]) / rate(prom_liver_remote_duration_seconds_count[1m])",
     "legendFormat": "{{function}} Avg"
    }
   ]
  },
  {
   "title": "Requests rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prom_liver_requests_total[1m])",
     "legendFormat": "HTTP {{code}}"
    }
   ]
  },
  {
   "title": "Request duration [1m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(prom_liver_request_duration_seconds_bucket[1m]))",
     "legendFormat": "percentile 90"
    },
    {
     "expr": "histogram_quantile(0.99, rate(prom_liver_request_duration_seconds_bucket[1m]))",
     "legendFormat": "percentile 99"
    },
    {
     "expr": "rate(prom_liver_request_duration_seconds_sum[1m]) / rate(prom_liver_request_duration_seconds_count[1m])",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Request bytes [1m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(prom_liver_response_size_bytes_bucket[1m]))",
     "legendFormat": "percentile 90"
    },
    {
     "expr": "histogram_quantile(0.99, rate(prom_liver_response_size_bytes_bucket[1m]))",
     "legendFormat": "percentile 99"
    },
    {
     "expr": "rate(prom_liver_response_size_bytes_bucket[5m]) / rate(prom_liver_response_size_bytes_bucket[5m])",
     "legendFormat": "Avg"
    }
   ]
  },
  { "title": "Go process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Memory in Off-Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{job=\"$job\"}"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{job=\"$job\"}"
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes{job=\"$job\"}"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{job=\"$job\"}"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{job=\"$job\"}"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{job=\"$job\"}"
    },
    {
     "expr": "go_memstats_other_sys_bytes{job=\"$job\"} - go_memstats_other_sys_bytes{job=\"$job\"}",
     "legendFormat": "bytes of memory are used for other runtime allocations {pod={{kubernetes_pod_name}}}"
    },
    {
     "expr": "go_memstats_next_gc_bytes{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"$job\"}"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{job=\"$job\"}"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{job=\"$job\"}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"$job\"}"
    },
    {
     "expr": "go_memstats_heap_released_bytes{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"$job\"}"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{job=\"$job\"} - go_memstats_frees_total{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated",
   "type": "graph",
   "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{job=\"$job\"}[1m])"
    }
   ]
  },
  {
   "title": "Rate of a Pointer Dereferences",
   "type": "graph",
   "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_lookups_total{job=\"$job\"}[1m])"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Rates of Allocation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"$job\"}[1m])"
    }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"$job\"}"
    }
   ]
  }
 ]
}