##################################################
#  example config
##################################################
server:
  proxy: "http://localhost:9090/"   #default http://localhost:9090
  port: 8080                        #default 8080
  authentication: true              #default true
  id-header: 'X-Prom-Liver-Id'    #default X-Prom-Liver-Id (could be reloaded)
  api-enable: true                #default true
  federate-enable: true           #default true

clients_files:
  - "examples/client*"

clients:
  'go-metrics': 
    auth:
      basic:
        user: user1
        password: password1
      header: true
      bearer:
        files:
          - "examples/secret_*"
    match:
      - '{project=~"go-.*"}'
      - '{env="test"}'
      - '{some=~".*oops.*"}'
  'cadvisor':
    auth:
      bearer:
        tokens: 
          - 'TESTTEST'
          - 'TESTTEST2'
    match:
      - 'up{project="cadvisor", env="test"}'

# curl -X GET http://localhost:8080/federate?match%5B%5D=up%7Bproject=%22go-metrics%22%7D -H "Authorization: Basic Y2Fkdmlzb3I6Y2Fkdmlzb3I=" -H "X-Prom-Liver-Id: go-metrics"
# curl -X GET http://localhost:8080/federate?match%5B%5D=up%7Bproject=%22cadvisor%22,%20env=%22test%22%7D -H "Authorization: Bearer TESTTEST"
# curl -X GET 'http://localhost:8080/api/v1/query?query=up%7Benv%3D%22test%22%2Cinstance%3D%22cadvisor%3A8080%22%2Cjob%3D%22cadvisor%22%2Cproject%3D%22cadvisor%22%7D&time=1567587907.668&_=1567587842765' -H "Authorization: Bearer TESTTEST"