##################################################
#  example config
##################################################
server:
  proxy: "http://localhost:9090/"   #default http://localhost:9090/
  port: 8080                        #default 8080
  uri: "/federate"                  #default /federate
  authentication: true              #default true
  id-header: 'X-Prom-Liver-Id'    #default X-Prom-Liver-Id (could be reloaded)

clients_files:
  - "examples/client*"

clients:
  'go-metrics': 
    auth:
      basic:
        user: user1
        password: password1
      header: true
      bearer:
        files:
          - "examples/secret_token.txt"
    match:
      - '{project=~"go-.*"}'
      - '{env="test"}'
      - '{some=~".*oops.*"}'
  'cadvisor':
    auth:
      bearer:
        tokens: 
          - 'TESTTEST'
          - 'TESTTEST2'
    match:
      - 'up{project="cadvisor", env="test"}'
