##################################################
#  example config
##################################################
server:
  proxy: "http://localhost:9090/"   #default http://localhost:9090/
  port: 8080                        #default 8080
  authentication: true              #default true
  id-header: 'X-Prom-Liver-Id'    #default X-Prom-Liver-Id

clients:
  - id: 'go-metrics'
    auth:
      basic:
        user: user1
        password: password1
      header: true
    match:
      - '{project=~"go-.*"}'
      - '{env="test"}'
      - '{some!~".*oops.*"}'
  - id: 'cadvisor'
    auth:
      basic:
        user: 'cadvisor'
        password: 'cadvisor'
      bearer:
        token: 'TESTTEST'
    match:
      - 'up{project="cadvisor", env="test"}'
    
# curl -X GET http://localhost:8080/federate?match%5B%5D=up%7Bproject=%22go-metrics%22%7D -H "Authorization: Basic Y2Fkdmlzb3I6Y2Fkdmlzb3I=" -H "X-Prom-Liver-Id: go-metrics"
# curl -X GET http://localhost:8080/federate?match%5B%5D=up%7Bproject=%22cadvisor%22,%20env=%22test%22%7D -H "Authorization: Bearer TESTTEST"